# Basic Information 
title: Rui Xie
title_zh: 谢睿
position: Associate Professor
affiliation: Department of Statistics & Data Science, and College of Nursing, University of Central Florida
affiliation_link: https://sciences.ucf.edu/statistics/aistats/
affiliation_logo: ./assets/img/ucf-logo.png
email: Rui.Xie (at) ucf.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: ruixie, rui xie, ruixie7, rui-xie-ucf, rui.xie.ucf
description: Rui Xie is an Associate Professor at the University of Central Florida. His research focuses on Statistics, Machine Learning, Data Science, Biostatistics, and AI for health and nursing.
canonical: https://ruixie7.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=dYTCyDoAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/rui-xie-ucf
orcid_id: https://orcid.org/0000-0001-9769-8131

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/prof_pic.jpeg
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon.ico

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true
footnote: Powered by Jekyll and Minimal Light theme.

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-136303932-1


# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
